## Data gathering for jason data

In [7]:
import pandas as pd

In [8]:
pd.read_json('iris.json')

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [9]:
pd.read_json('https://jsonplaceholder.typicode.com/posts')

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

## my sql Connector

In [10]:
%pip uninstall mysql-connector-python mysql.connector -y

Found existing installation: mysql-connector-python 9.7.0
Uninstalling mysql-connector-python-9.7.0:
  Successfully uninstalled mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\uninstall.py", line 97, in run
    uninstall_pathset.commit()
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\req\req_uninstall.py", line 436, in commit
    self._moved_paths.commit()
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\req\req_uninstall.py", line 287, in commit
    save_dir.cleanup()
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\temp_dir.py", line 184, in cleanup
    rmtree(self._path)
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\misc.py", line 135, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\aboyc\\AppData\\Local\\Temp\\pip-uninstall-lkr5e4lg\\libcrypto-3-x64.dll'

In [11]:
%pip install mysql-connector-python

Collecting mysql-connector-python
  Using cached mysql_connector_python-9.7.0-cp310-cp310-win_amd64.whl (17.7 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [12]:
import mysql.connector

try:
    connection = mysql.connector.connect(
        host='localhost',
        user='root',
        password='',
        database='world',
        port=3306  # ⚠️ Change to 3307 if you changed XAMPP's port!
    )
    
    if connection.is_connected():
        print("🚀 Successfully connected using mysql-connector-python!")
        
        # Quick test to see if it works
        db_info = connection.get_server_info()
        print(f"MySQL Server version: {db_info}")
        
        connection.close()

except Exception as e:
    print(f"❌ Connection failed: {e}")

🚀 Successfully connected using mysql-connector-python!
MySQL Server version: 5.5.5-10.4.32-MariaDB

C:\Users\aboyc\AppData\Local\Temp\ipykernel_37860\2148850279.py:16: DeprecationWarning: Call to deprecated function get_server_info. Reason:
    The property counterpart 'server_info' should be used instead.

  db_info = connection.get_server_info()

In [13]:
data = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [14]:
data

In [15]:
df = pd.read_sql_query('select * from city', data)

C:\Users\aboyc\AppData\Local\Temp\ipykernel_37860\2165510187.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from city', data)

In [16]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [17]:
pd.read_sql_query('select * from city where CountryCode like"IND"',data)

C:\Users\aboyc\AppData\Local\Temp\ipykernel_37860\521834617.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from city where CountryCode like"IND"',data)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]