## Data Gathering

pd.read_csv

In [1]:
import pandas as pd

df = pd.read_csv(r'C:\Users\aboyc\tutedude\ML\Data Gathering\katalog_gempa_v2.tsv')

In [2]:
df

                                                   eventID\tdatetime\tlatitude\tlongitude\tmagnitude\tmag_type\tdepth\tphasecount\tazimuth_gap\tlocation\tagency\tdatetimeFM\tlatFM\tlonFM\tmagFM\tmagTypeFM\tdepthFM\tphasecountFM\tAzGapFM\tscalarMoment\tMrr\tMtt\tMpp\tMrt\tMrp\tMtp\tvarianceReduction\tdoubleCouple\tclvd\tstrikeNP1\tdipNP1\trakeNP1\tstrikeNP2\tdipNP2\trakeNP2\tazgapFM\tmisfit
bmg2008vkye\t2008-11-01 00:31:25.143741+00:00\t...   Indonesia\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2008vlag\t2008-11-01 01:34:29.660856+00:00\t...                                                NaN
bmg2008vlaj\t2008-11-01 01:38:14.802129+00:00\t...   Indonesia\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2008vlbt\t2008-11-01 02:20:05.909515+00:00\t...                                                NaN
bmg2008vlcd\t2008-11-01 02:32:18.756155+00:00\t...                                                NaN
...                                                                                               ...
bmg2025tfhc\t2025-10-01 06:27:13.361342+00:00\t...   Indonesia\tBMKG\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2025tfjc\t2025-10-01 07:27:26.179947+00:00\t...   Indonesia\tBMKG\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2025tfml\t2025-10-01 09:08:34.331422+00:00\t...   Indonesia\tBMKG\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2025tfor\t2025-10-01 10:16:04.080532+00:00\t...                                                NaN
bmg2025tftc\t2025-10-01 12:30:19.302639+00:00\t...   Sulawesi\tBMKG\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\...

[131833 rows x 1 columns]

In [3]:
df = pd.read_csv(r'C:\Users\aboyc\tutedude\ML\Data Gathering\Titanic-Dataset.csv',names=['P_ID','Survived','Pclass','P_name','Gender','Age','Sibiling or Spouse','Parch','Ticket_ID','Fare','Cabin','Starting Journey'])

In [4]:
df

,P_ID,Survived,Pclass,P_name,Gender,Age,Sibiling or Spouse,Parch,Ticket_ID,Fare,Cabin,Starting Journey
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q

In [5]:
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True).set_index('PassengerId')

In [6]:
df_student = pd.read_csv('student_depression_dataset.csv')

df_student = df_student.rename(columns={
    'Gender': 'gender',
    'Age': 'age',
    'City': 'city',
    'Profession': 'profession',
    'Academic Pressure': 'academic_pressure',
    'CGPA': 'cgpa',
    'Study Satisfaction': 'study_satisfaction',
    'Job Satisfaction': 'job',
    'Sleep Duration': 'sleep_duration',
    'Dietary Habits': 'dietary_habits',
    'Degree': 'degree_satisfaction',
    'Have you ever had suicidal thoughts ?': 'have_you_ever_had_suicidal_thoughts',
    'Depression': 'depression'
})[cols]

NameError: name 'cols' is not defined

In [ ]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q

In [ ]:
cols = [
    'id', 'gender', 'age', 'city', 'profession',
    'academic_pressure', 'cgpa', 'study_satisfaction',
    'job', 'sleep_duration', 'dietary_habits',
    'degree_satisfaction',
    'have_you_ever_had_suicidal_thoughts',
    'depression'
]

df_student = pd.read_csv('student_depression_dataset.csv')
df_student.columns = cols
d

ValueError: Length mismatch: Expected axis has 18 elements, new values have 14 elements

In [7]:
df = pd.read_csv(r'C:\Users\aboyc\tutedude\ML\Data Gathering\Titanic-Dataset.csv',usecols=['Survived']).squeeze()

In [8]:
df

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [9]:
pd.read_csv('Titanic-Dataset.csv', encoding='latin-1')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:
pd.read_csv('student_depression_dataset.csv',dtype={'Age':int,'Work Pressure':int})

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33,Visakhapatnam,Student,5.0,0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24,Bangalore,Student,2.0,0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31,Srinagar,Student,3.0,0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28,Varanasi,Student,3.0,0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25,Jaipur,Student,4.0,0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27,Surat,Student,5.0,0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27,Ludhiana,Student,2.0,0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31,Faridabad,Student,3.0,0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18,Ludhiana,Student,5.0,0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27,Patna,Student,4.0,0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [ ]:
pd.read_csv('student_depression_dataset.csv',dtype={'Age':int,'Work Pressure':int})